"""company table

Revision ID: 03fae64bc19e
Revises: 8aca311750d3
Create Date: 2020-06-18 02:31:19.897276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03fae64bc19e'
down_revision = '8aca311750d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('company', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_company_timestamp'), 'company', ['timestamp'], unique=False)
    op.create_foreign_key(None, 'company', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.drop_index(op.f('ix_company_timestamp'), table_name='company')
    op.drop_column('company', 'user_id')
    op.drop_column('company', 'timestamp')
    # ### end Alembic commands ###
